### ISSUE TITLE
Timeout near the last step

### ISSUE THREAD

**Issue by atkulp** [william-sy/sonoff-zbdongle-p-fw-mac-Lin#2]
Everything looks good until the second time I enter the serial port. Have you seen this? Any idea what the problem could be?

```
# Please supply the serial port again:
/dev/ttyUSB0
# Flashing the device:
sonoff
Opening port /dev/ttyUSB0, baud 500000
Reading data from CC1352P2_CC2652P_launchpad_coordinator_20221226.hex
Firmware file: Intel Hex
Connecting to target...
CC1350 PG2.0 (7x7mm): 352KB Flash, 20KB SRAM, CCFG.BL_CONFIG at 0x00057FD8
Primary IEEE Address: 00:12:4B:00:24:C0:B6:94
    Performing mass erase
Erasing all main bank flash sectors
    Erase done
Writing 360448 bytes starting at address 0x00000000
ERROR: Timeout waiting for ACK/NACK after 'Get Status (0x23)'
```

**Comment by william-sy** [comment]
Hi, 

No I have never seen this, as I am only gluing other scripts together, its also not something I can perse fix. 

It looks like your USB stick got disconnected / moved / wiggled during the upgrade procedure.
It started writing, but after that it lost connection so something made the stick "reboot" and that closed the ability to write to the stick. 

You could retry the upgrade, see if that will solve it.

**Comment by atkulp** [comment]
I've tried over and over and even different ports. I realized what you said about the scripts though so I'll open a ticket in the right repo! Thanks for your work on assembling this though. Much easier to use than the raw tools.

**Comment by william-sy** [comment]
No problem :) happy to help!

(Try opening the stick up, there are physical buttons on the PCB perhaps you can force the boot by pressing the boot button, last but not least, a different pc just in case)
